### ISSUE TITLE
USER STORY: Create Account

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#1]
As a **new user**, I can **create an account** so that I can **get access to all features of the application**.

### Acceptance Criteria
- [x] The user can enter a username, email address, and password.
- [x] The user can submit the form.
- [x] The user will receive appropriate error messages.
- [x] The user is redirected to the login page.

### Task
- [x] Create sign up form component
- [x] Setup axios
- [x] Connect form to API
