### ISSUE TITLE
USER STORY: Edit Sound File Information

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#10]
As a **registered user**, I can **edit information for my sound file** so that I can **update my sound's details**.

### Acceptance Criteria
- [x] The user can update the title, description, and tags.
- [x] The user can upload a new sound file
- [x] The user can upload a new image.
- [x] The user can update the location on a map.
- [x] The user can submit the form.
- [x] The user is redirected to the sound detail page.

### Tasks
- [x] Create edit sound form
- [x] pass previous sound data to fields
- [x] send updated data to API
- [x] Redirect to sound detail page
