### ISSUE TITLE
USER STORY: See List of Sound Files

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#11]
As a **registered user**, I can **see a list of sound files** so that I can **explore other user's sounds**.

### Acceptance Criteria
- [x] The user can see a list of sound files.
- [x] The user can see the sound's details (title, description, image, tags, location, likes, number of comments etc.).
- [x] The user can play the sound file from the list.
- [x] The user can click on a sound to access the sound detail page.

### Tasks
- [x] Create sound list page
- [x] Add routes
- [x] Send API request to get all sounds
- [x] Display list of sounds
