### ISSUE TITLE
USER STORY: Sort and Filter List of Sound Files

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#12]
As a **registered user**, I can **sort and filter the list of sound files** so that I can **easily find specific sounds**.

### Acceptance Criteria
- [ ] The user can sort the list of sound files by date, by popularity and other criteria.
- [ ] The user can filter the list of sound files by tags or by uploader.
- [ ] The user can see the number of results for each filter.

### Tasks
