### ISSUE TITLE
USER STORY: Search for Sound Files

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#13]
As a **registered user**, I can **search for sound files** so that I can **find specific sounds easily**.

### Acceptance Criteria
- [x] The user can enter a search term.
- [x] The matching sounds will be displayed in real time as the user types.

### Tasks
- [x] Include search bar in post list page
- [x] Get search query from user input
- [x] Add search filter with query from search bar to API request
