### ISSUE TITLE
USER STORY: Sound Feed with Sounds from Followed Users

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#14]
As a **registered user**, I can **see a sounds feed with sounds from followed users** so that I can **discover content from users I follow**.

### Acceptance Criteria
- [x] The user can see a list of sound files from followed users.
- [x] The user can see the sound's details (title, description, image, tags, location, likes, number of comments etc.).
- [x] The user can play the sound file from the list.
- [x] The user can click on a sound to access the sound detail page.

### Tasks
- [x] Add filter to sound list page to filter out sounds by users the current user is following
- [x] Add Feed route
