### ISSUE TITLE
USER STORY: See List of Liked Sounds

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#15]
As a **registered user**, I can **see a list of sound files I liked** so that I can **access my favourite sounds**.

### Acceptance Criteria
- [x] The user can see a list of sound files they liked.
- [x] The user can see the sound's details (title, description, image, tags, location, likes, number of comments etc.).
- [x] The user can play the sound file from the list.
- [x] The user can click on a sound to access the sound detail page.

### Tasks
- [x] Add filter to sound list page to get sounds the user liked
- [x] Add route
