### ISSUE TITLE
USER STORY: Access Sound Detail Page

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#17]
As a **registered user**, I can **access a sound detail page with an audio player and the sound's details** so that I can **get more information on a specific sound**.

### Acceptance Criteria
- [ ] The user can access a sound detail page by clicking on a sound in the list of sounds or on a map marker.
- [x] The user can see the sound's details (title, description, image, tags, location, likes, number of comments etc.).
- [x] The user can play the sound file from the audio player.

### Tasks
- [x] Create sound detail component
- [x] Create sound page
- [x] Add sound details to sound detail component
- [x] Create route
- [x] Include audio player
- [x] Link to sound detail page from sound list
