### ISSUE TITLE
USER STORY: Location Data on Sound Detail Page

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#18]
As a **registered user**, I can **see a map with the sound's location on the sound detail page** so that I can **see the sound's location without going to the map view**.

### Acceptance Criteria
- [x] The user can see a map with the sound's location on the sound detail page.

### Tasks
- [x] Create map component using leaflet
- [x] Import map component in sound detail page
- [x] Show marker on map according to sound location data
