### ISSUE TITLE
USER STORY: Like and Unlike Sounds

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#19]
As a **registered user**, I can **like and unlike sounds** so that I can **express my appreciation for other user's sounds**.

### Acceptance Criteria
- [x] The user can like a sound.
- [x] The user can unlike a sound.
- [x] The user can see the number of likes for each sound.
- [x] The number of likes is updated.

### Tasks
- [x] Add function for handling liking and unliking sounds
- [x] Make post/delete request to API for creating and deleting likes
