### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#2]
As a **registered user**, I can **log in** so that I can **access my account**.

### Acceptance Criteria
- [x] The user can enter their username and password.
- [x] The user can submit the form.
- [x] The user is redirected to the home page.

### Tasks
- [x] Create sign-in form
- [x] make login request with axios
- [x] redirect to home page
