### ISSUE TITLE
USER STORY: Edit and Delete Comments

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#21]
As a **registered user**, I can **edit and delete my comments** so that I can **correct mistakes or withdraw comments**.

### Acceptance Criteria
- [x] The user can edit own comments.
- [x] The user can delete own comments.
- [x] The user can see the updated comment on the sound detail page.
- [x] The user can see that the comment was deleted on the sound detail page.

### Tasks
- [x] Add handleDelete function to comment component to send DELETE request to API
- [x] Display confirmation modal before deleting comment
- [x] Add editing form for comment and create logic for displaying either a comment or the edit form.
- [x] Send PUT request to API with new comment data from edit form
- [x] Update comment list on sound detail page with new comment data
