### ISSUE TITLE
USER STORY: Follow/Unfollow Other Users

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#22]
As a **registered user**, I can **follow and unfollow other users** so that I can **stay updated on their uploaded content**.

### Acceptance Criteria
- [x] The user can follow other users.
- [x] The user can unfollow other users.
- [x] The user can see the number of followers for each user.
- [x] The number of followers is updated.

### Tasks
- [x] Create handleFollow and handleUnfollow functions for making POST and DELETE API requests
- [x] Update Follow count and follow button in profile page and popular profiles components
