### ISSUE TITLE
USER STORY: See Most Followed Users Widget

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#23]
As a **registered user**, I can **see a widget with a list of the most followed users** so that I can **discover popular users**.

### Acceptance Criteria
- [x] The user can see a widget with a list of the most followed users.
- [x] The user can click on a user to access the user's profile page.

### Tasks
- [x] Create responsive component for displaying popular profiles
- [x] Create context for fetching profile data from the API and making it available across all components
- [x] Create profile component for displaying profiles in the widget
