### ISSUE TITLE
USER STORY: Receive Notifications for New Sounds by Followed Users

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#24]
As a **registered user**, I can **receive notifications for new sounds by followed users** so that I can **stay updated on their content**.

### Acceptance Criteria
- [ ] The user can see new notifications in the notification inbox.
- [ ] The user can see the number of new notifications in the navigation bar.
- [ ] The user can click on a notification to read it.
- [ ] The user can mark notifications as read.

### Tasks
