### ISSUE TITLE
USER STORY: Receive Notifications for New Likes, Comments, and Followers

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#25]
As a **registered user**, I can **receive notifications for new likes, comments, and followers** so that I can **stay engaged with my followers**.

### Acceptance Criteria
- [x] The user can see new notifications in the notification inbox.
- [x] The user can mark notifications as read.
- [x] The user can delete notifications.

### Tasks
- [x] Create notification page and notification component
- [x] Retrieve notifications from API and list them on notification page
- [x] Create handleDelete and handleUpdate functions for updating and deleting notifications
- [x] Display notifications as read or unread depending on is_read status
