### ISSUE TITLE
USER STORY: Receive Notifications for New Reports

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#26]
As a **staff user**, I can **receive notifications for new reports** so that I can **take appropriate action on flagged content**.

### Acceptance Criteria
- [x] The user can see new report notifications in the notification inbox.
- [x] The user can click on a link to get to the report page from the notification.

### Tasks
- [x] Add condition for displaying report notifications to notification component
- [x] Link to reports page and to reported sound from report notification
