### ISSUE TITLE
USER STORY: Mark Reports as done

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#29]
As a **staff user**, I can **mark reports as done** so that I can **keep track of which reports still need to be reviewed**.

### Acceptance Criteria
- [x] The user can see a list of reports on a report page.
- [x] The user can mark reports as done from the report page.

### Tasks
- [x] Display all reports on a reports page by fetching all reports from the api.
- [x] Display link to reports page in user dropdown menu for staff users
- [x] Add handle function for sending patch request to API to update report review status 
- [x] Create buttons for marking reports as open or closed.
