### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#3]
As a **logged-in user**, I can **log out** so that I can **securely end my session**.

### Acceptance Criteria
- [x] The user can click on a logout button.
- [x] The user is redirected to the home page.

### Task
- [x] Create handleSignOut function in NavBar component
- [x] Make request from handleSignOut function to API to log out user
