### ISSUE TITLE
USER STORY: Delete Reports

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#30]
As a **staff user**, I can **delete reports** so that I can **get rid of inappropriate reports or reports that are no longer relevant**.

### Acceptance Criteria
- [x] The user can delete reports from the report detail page.
- [x] The user can see a confirmation message.

### Tasks
- [x] Create handleDelete function on reports component to make DELETE request to reports/id endpoint
- [x] Add delete button to report component
