### ISSUE TITLE
USER STORY: See a Map with All Uploaded Sounds as Map Markers

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#31]
As a **registered user**, I can **see a map with all uploaded sounds as map markers** so that I can **explore sounds based on their location**.

### Acceptance Criteria
- [x] The user can see a map with all uploaded sounds as map markers.
- [x] The user can click on a map marker to open a popup with the sound's details including an audio player.
- [x] The user can click on a link in the popup to access the sound detail page.

### Tasks
- [x] Create Map component 
- [x] Fetch all sounds from the API
- [x] Loop over results and create location marker for each sound
- [x] Add sound details to marker popup
