### ISSUE TITLE
USER STORY: Filter Sounds Displayed on the Map

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#32]
As a **registered user**, I can **filter sounds displayed on the map** so that I can **limit the sounds displayed on the map to match specific criteria**.

### Acceptance Criteria
- [x] The user can filter sounds displayed on the map by tags, by uploader and other criteria.

### Tasks
- [x] Add search bar to map view
- [x] Add search query to API request and fetch new data if query exists
- [x] Update sounds data
