### ISSUE TITLE
USER STORY: Intuitive Navigation

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#33]
As a **user**, I can **navigate through the application intuitively** so that I can **easily find the features I am looking for**.

### Acceptance Criteria
- [x] The user can see a navigation bar with links to the most important features, like Explore, Feed, Liked, Profiles, Map etc.
- [x] The user can see links to sign up/log in or log out depending on whether they are logged-in or not.

### Tasks
- [x] Install and setup react-router-dom
- [x] Create NavBar component
- [x] Import NavBar component
- [x] Add css module for NavBar
- [x] Conditionally display nav items depending on if user is authenticated and staff user.
