### ISSUE TITLE
USER STORY: Responsive and Consistent Design

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#34]
As a **user**, I can **access the application from different devices with a responsive and consistent design** so that I can **experience the same features and design on all devices**.

### Acceptance Criteria
- [x] The website is responsive and displays correctly on all screen sizes.
- [x] The website has a consistent design on all pages.

### Tasks
- [x] Use responsive layout in all components and all pages
- [x] Make sure that all text has enough space or wraps
- [x]  Use consistent colors, fonts, and font sizes on all elements.
