### ISSUE TITLE
USER STORY: Display Messages

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#35]
As a **user** I want to **see messages as feedback for my actions within the application** so that I can **know if my actions were successful**.

### Acceptance Criteria
- [x] The user can see appropriate messages as feedback for user actions.

### Tasks
- [x] Create Message component
- [x] Add function for displaying messages to App.js
- [x] Pass function for creating messages to child components
