### ISSUE TITLE
USER STORY: Audio Player

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#38]
As a **user**, I can **access an audio player** so that I can l**isten to my own and other user's sounds**.

### Acceptance Criteria
- [x] There is an audio player for listening to sounds.
- [x] The user can click on play and listen to a sound.
- [x] The user can pause and resume the playback.
- [x] The user can see how long the sound is an the playback progress.

### Tasks
- [x] Create audio player component
- [x] User wavesurfer.js for audio playback and waveform rendering
- [x] Audio player component accepts audio url as input.
