### ISSUE TITLE
USER STORY: View Profile

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#4]
As a **registered user**, I can **click on a profile link in the menu** so that I can **review my profile or check out other user's profiles**.

### Acceptance Criteria
- [x] The user can see a profile page where they can see their profile data.
- [x] The user can see other user's profile pages.

### Tasks
- [x] Create profile page
- [x] Get profile information from API
- [x] Display profile information on profile page (avatar, followers, sounds etc.)
- [x] Conditionally display follow/unfollow button
