### ISSUE TITLE
USER STORY: Delete Sounds

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#42]
As **the owner of a sound**, I can **delete sounds** so that I can **remove sounds I don't need anymore**.

### Acceptance Criteria
- [x] The user can click on a delete button to delete a sound.
- [x] The user will be asked for confirmation.
- [x] The sound will be deleted from the database.

### Tasks
- [x] Add delete button to sound detail component
- [x] Add confirmation modal component to confirm deletion
- [x] Create handleDelete function and call it from confirmation modal
