### ISSUE TITLE
USER STORY: Edit Profile

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#5]
As a **registered user**, I can **edit my profile** so that I can **update my information**.

### Acceptance Criteria 
- [x] The user can go to their profile page and click on a link to edit their profile.
- [x] The user can update their data like profile image, description, and display name.
- [x] The user can change the username.
- [x] The user can change the password.
- [x] The user is redirected to the profile page upon submitting the form.

### Tasks
- [x] Create profile edit form with fields to edit profile image, display name, and description
- [x] Make PUT request on submit to send new data to API
- [x] Create username edit form and send PUT request to dj-rest-auth/user endpoint
- [x] Create password edit form and send PUT request to dj-rest-auth/password/change endpoint
- [x] Redirect to home if user is not profile owner
- [x] Redirect user to profile page upon submit
