### ISSUE TITLE
USER STORY: Upload Sound File

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#6]
As a **registered user**, I can **upload a sound file** so that I can **share my sounds with other users**.

### Acceptance Criteria
- [x] The user can upload a sound file.
- [x] The user can submit the form.
- [x] The user is redirected to the sound detail page.

### Tasks
