### ISSUE TITLE
USER STORY: Record Sound File

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#7]
As a **registered user**, I can **record a sound file** so that I can **create and share new sounds on the spot**.

### Acceptance Criteria
- [ ] The user can record a sound file.
- [ ] The user can replay the recording.
- [ ] The user can re-record the sound file.
- [ ] The user can submit the form.
- [ ] The user is redirected to the sound detail page.

### Tasks
