### ISSUE TITLE
USER STORY: Add Geolocation Data to Sound File

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/sonic-explorers#9]
As a **registered user**, I can **add geoloaction data to my sound file, either by choosing a location on a map or by allowing the browser to access my location** so that I can **provide location data for my sounds**.

### Acceptance Criteria
- [x] The user can choose a location on a map.
- [x] The user can allow the browser to access their location.
- [x] The user can submit the form.

### Tasks
- [x] Install and setup react-leaflet
- [x] Access HTML Geolocation API
- [x] Write functions for handling location retrieval and displaying map
- [x] Add Map component using leaflet
